### ISSUE TITLE
does this module still work on Meteor 0.6.4 ?

### ISSUE THREAD

**Issue by ChJJin** [erobit/meteor-accounts-ui-bootstrap-dropdown#26]
because of some reasons, I am using this module on Meteor 0.6.4.
but the following error occurred:

```
Exception while bundling application:
TypeError: Object #<Object> has no method 'imply'
```

and I modify the smart.lock to use earlier version, but it doesn't work, 
a new error came out:  `webapp` package not found

**Comment by lc3t35** [comment]
Adding the package manually, I have the same error with Windows current version from win.meteor.com

**Comment by ChJJin** [comment]
@lc3t35  I think our errors are the same because the Meteor for Windows is based on meteor-0.6.4.1 .

Now, I can only use an earlier release of the package I have ever backed up to make it works.

**Comment by lc3t35** [comment]
i moved to a linux virtual box with vagrant in order to run the lastest version of meteor.
Just forward the port 3000, then you can expose the meteor server in Windows.
Install madeye.io (https://github.com/mad-eye) in your linux box, then you can share and edit the source tree from any external navigator within Windows or with another remote pair programmer.

**Comment by dandv** [comment]
It certainly won't work with Blaze. I'm using [this fork](https://github.com/mangasocial/meteor-accounts-ui-bootstrap-3) instead.

**Comment by ChJJin** [comment]
@dandv thanks. And finally, I update Meteor to the version 0.7.0.1 on both linux and window
